# Eureka Server Port
server.port=8761

# Application Name
spring.application.name=eureka-server

# Since this is a standalone registry, we disable peer replica awareness and registry fetching
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Set logging levels to observe instance registrations
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
logging.level.org.springframework.cloud=INFO
